### ISSUE TITLE
uniform code

### ISSUE THREAD

**Issue by benkimo6i** [Aurelius180/group_project_1#2]
- fix navbar, make it look pretty!

**Comment by Aurelius180** [comment]
"Pretty" is kind of subjective, but here goes nothing.

**Comment by Aurelius180** [comment]
[main.css.zip](https://github.com/Aurelius180/group_project_1/files/310383/main.css.zip)

**Comment by Aurelius180** [comment]
Is it everything you hoped for?

**Comment by Virginia-Rucinski** [comment]
Hi!  Done "working" on my "job" for today.  Working on this now.  Copied Ben's updates to Navbar - yes, pretty.  Kyle, did you solve your issue with your pic?

**Comment by benkimo6i** [comment]
new navbar has already  been uploaded to master branch, issue resolved!
