### ISSUE TITLE
Woe is me, my picture is off-center

### ISSUE THREAD

**Issue by Aurelius180** [Aurelius180/group_project_1#3]
I have a pretty cool, artsy honeybee picture on my page. However, there is an issue with it. It is not perfectly centered! This ruins my page and makes me morbidly depressed. Sorry, everyone.

If anyone can solve this problem, not only will I be impressed, but I'll have a better opinion of you in general.

So really, you have a lot to gain by helping me.

**Comment by benkimo6i** [comment]
I got this one, let me see if I can fix it.

**Comment by benkimo6i** [comment]
Fixed it
![screen shot 2016-06-12 at 18 23 39](https://cloud.githubusercontent.com/assets/19436184/15994163/e5d5ce06-30ca-11e6-8fbd-adb4f707e0c3.png)
